spring.application.name=PaynowSpringBootIntegration
paynow.integration.id=1234
paynow.integration.key=01234-56789
paynow.resultUrl=http://yourdomain.com/paymentupdatereceiver
paynow.returnUrl=http://yourdomain.com/return?gateway=paynow&reference=123
