=spring:
  application:
    name: PaynowSpringBootIntegration

  datasource:
    url: jdbc:h2:mem:paynowdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
      path: /h2-console

paynow:
  integration:
    id: ${INTERGRATION_ID}
    key: ${INTERGRATION_KEY}
  result:
    url: http://localhost:8080/api/payments/update
  return:
    url: http://localhost:63342/Paynow-Intergration/paynow-Integration/static/payment-complete.html?_ijt=qeam4s4e8fhs9imbo4qb07r9g7&_ij_reload=RELOAD_ON_SAVE

server:
  port: 8080

spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
